Simplify
There was no need for a step on its own to fail the workflow.

diff --git a/.github/workflows/labels.yml b/.github/workflows/labels.yml
--- a/.github/workflows/labels.yml
+++ b/.github/workflows/labels.yml
@@ -57,11 +57,8 @@ jobs:
                   gh pr comment $URL --body "$(echo -e $COMMENT_TEXT)"
                 fi
 
-            - name: 'Fail'
-              uses: actions/github-script@v7
-              if: env.labels_are_missing == 'true'
-              with:
-                  script: core.setFailed('Required doc and/or ui labels missing.')
+                echo "::error::Required doc and/or ui labels missing."
+                exit 1
 
             - name: Hide comment when resolved
               if: env.labels_are_missing != 'true'
